### ISSUE TITLE
Can this repo be moved to the graveyard?

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/PERA-Embedded#1]
@ruudbogaert @jlunenburg 

Is this still active and do we need this? If not, I will move it from this organization to the graveyard.

**Comment by ruudbogaert** [comment]
Not active, github is not suitable for FPGA hardware developement

Sent from my mobile device, please excuse my brevity

Op 16 nov. 2016 om 14:24 heeft Rein Appeldoorn <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

@ruudbogaerthttps://github.com/ruudbogaert @jlunenburghttps://github.com/jlunenburg

Is this still active and do we need this? If not, I will move it from this organization to the graveyard.

**Comment by reinzor** [comment]
I will move this to the graveyard then ..
